# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veil < Formula
  desc "Veil - An opinionated, fully featured, modular observability stack for APIs. Allows you to sell, monitor, authenticate your APIs."
  homepage "https://github.com/try-veil/veil"
  version "0.0.0-release-test"
  license "MIT"

  depends_on "xcaddy"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/try-veil/veil/releases/download/v0.0.0-release-test/veil_0.0.0-release-test_Darwin_arm64.tar.gz"
      sha256 "fa07a884983aa3051c83325e65d5ff8754f2bebf4a682706c7ef98c3821af78e"

      def install
        bin.install "veil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/try-veil/veil/releases/download/v0.0.0-release-test/veil_0.0.0-release-test_Linux_x86_64.tar.gz"
        sha256 "9429306bfb236e745dd8205727900a12ff13415a2a11e65ba483f0ee13c11517"

        def install
          bin.install "veil"
        end
      end
    end
  end

  test do
    system "#{bin}/veil version"
  end
end
