# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veil < Formula
  desc "Veil - An opinionated, fully featured, modular observability stack for APIs. Allows you to sell, monitor, authenticate your APIs."
  homepage "https://github.com/try-veil/veil"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/try-veil/veil/releases/download/v0.0.2/veil_0.0.2_Darwin_arm64.tar.gz"
      sha256 "e2c73140085a0d077f2da1768a9765c892098cdfb3945ed495014ed6ab74a782"

      def install
        bin.install "veil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/try-veil/veil/releases/download/v0.0.2/veil_0.0.2_Linux_x86_64.tar.gz"
        sha256 "c90c9eb228d83d5932fce7db957c42fc67f6615c4533f184834cd0333ee2f23e"

        def install
          bin.install "veil"
        end
      end
    end
  end

  test do
    system "#{bin}/veil version"
  end
end
