# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veil < Formula
  desc "Veil - An opinionated, fully featured, modular observability stack for APIs. Allows you to sell, monitor, authenticate your APIs."
  homepage "https://github.com/try-veil/veil"
  version "0.0.0-gorelease-test"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/try-veil/veil/releases/download/v0.0.0-gorelease-test/veil_0.0.0-gorelease-test_Darwin_arm64.tar.gz"
      sha256 "dba0fade340c12f2110c511be0b29ea0ae923ac8d15d937955400832d84fdd54"

      def install
        bin.install "veil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/try-veil/veil/releases/download/v0.0.0-gorelease-test/veil_0.0.0-gorelease-test_Linux_x86_64.tar.gz"
        sha256 "36cce7aa1c1cbc70b54fcba0d46d7b0565e1ca41327478308f59f72db0cdc562"

        def install
          bin.install "veil"
        end
      end
    end
  end

  test do
    system "#{bin}/veil version"
  end
end
